server:
  port: 8123
  forward-headers-strategy: framework

spring:
  application:
    name: auction-service

  datasource:
    url: jdbc:mysql://localhost:3306/piece_of_cake_local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379
    username: redis123
    password: 1234

  config:
    import: optional:file:.env[.properties]

kafka:
  bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    batch-size: 16384
    linger-ms: 10
    buffer-memory: 33554432
    acks: all
    retries: 3
  consumer:
    group-id: bid-batch-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    enable-auto-commit: false
    max-poll-records: 100
    auto-offset-reset: earliest

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
